### PR TITLE
Add 3-series Card Support

### LINKED ISSUE #125: Add support for Expansion card cages

### PR DESCRIPTION
**Pull request by andrew-welker**
closes #125 

This PR adds support for 3-Series card cages and all 5 cards. See attached file for test configuration. Prior to approving this, please test against hardware to verify operation.
[democonfigurationFile.txt](https://github.com/PepperDash/Essentials/files/4800050/democonfigurationFile.txt)

### CODE REVIEW

**Comment by ndorin** [comment]
Are we sure we want the internal card cage to be a separate device in config rather than an object on the processor device?

**Comment by andrew-welker** [comment]
My thought is that having it as a separate device makes it easier to manage. There are only 2 models of processors that even have the capability to use the cards internally. Using the external device gives us some protections (that could, admittedly, be built into the processor too) as I'm checking if the control system supports the cards prior to trying to instantiate them.

**Comment by andrew-welker** [comment]
Rebased this branch

**Comment by ndorin** [comment]
Fair point. And as the config expert now, I defer to your expertise. Carry on!

Sent from my iPhone

On Jun 18, 2020, at 6:52 PM, Andrew Welker <notifications@github.com> wrote:

﻿

My thought is that having it as a separate device makes it easier to manage. There are only 2 models of processors that even have the capability to use the cards internally. Using the external device gives us some protections (that could, admittedly, be built into the processor too) as I'm checking if the control system supports the cards prior to trying to instantiate them.

**Comment by aknous** [comment]
I was just able to successfully register one internal card cage using 2 C3-COM3 cards. Not yet able to test comms through them yet, but so far so good.

**Pull request merged**
