### PR TITLE
Feature/local config notice

### LINKED ISSUE #399: [FEATURE]-Add OBVIOUS (ASCII Art maybe?) message to indicated when Essentials loads a local config file
**Is your feature request related to a problem? Please describe.**
When Essentials loads a local config file (written by Essentials to the LocalConfig folder) it's not obvious to the developer that it's not using the config file in the root user folder for that program slot.  This can cause a fair amount of wasted time when making changes to the main config file but the program is using the local file and ignoring your new changes

**Describe the solution you'd like**
Add a very obvious message block in console to alert the developer

### PR DESCRIPTION
**Pull request by TrevorPayne**
This look alright to you?

Resolves #399 

image

### CODE REVIEW

**Review by andrew-welker — COMMENTED** [review]
I like it...lets get some input from the rest of the team too...

**Comment by TrevorPayne** [comment]
I was so close to just porting over an entire ASCII Art library just to do this - would be a fun little addition, but this was super quick.

**Review by andrew-welker — CHANGES_REQUESTED** [review]
The consensus from the team was that we're looking for something more like:
```
******************************************************
************* Using Local config file *****************
******************************************************
```

**Comment by ndorin** [comment]
> The consensus from the team was that we're looking for something more like:
> 
> ```
> ******************************************************
> ************* Using Local config file *****************
> ******************************************************
> ```

Agreed, something simpler like this, but including the path the the actual file that is loaded

**Comment by TrevorPayne** [comment]
Updated - Client name redacted with a lovely red squiggle!

image

**Comment by TrevorPayne** [comment]
New Example

Client name redacted by lovely red squiggles.

image

**Review by andrew-welker — APPROVED** [review]

**Pull request merged**
