### PR TITLE
VISCA Camera improvements

### LINKED ISSUE #412: [BUG]-CameraVisca Power Feedback
**Describe the bug**
CameraVisca is not parsing power feedback from the device and in turn PowerIsOn property is not being set.  The PowerToggle method is referencing the PowerIsOn property.

**Expected behavior**
Communication_BytesReceived parse the necessary device responses.

### LINKED ISSUE #413: [FEATURE]- Update configuration for CameraVisca
**Is your feature request related to a problem? Please describe.**
1. CameraPropertiesConfig does not include a configuration for Camera ID
2. No configuration for pan, tilt  speeds

**Describe the solution you'd like**
1. Extend CameraPropertiesConfig to create CameraViscaPropertiesConfig
1. Add support for Camera ID through configuration. 
1. Add configuration for pan, tilt slow/fast speeds and FastSpeedHoldTime.  If not defined a default value would be used.

### PR DESCRIPTION
**Pull request by ndorin**
Closes #412 
Closes #413 

@jkdevito the alpha build generated from this branch should be tested on real hardware before we approve this PR into development.  Is that something you might have access to gear to test?

### CODE REVIEW

**Comment by ndorin** [comment]
@jkdevito You'll want to test 1.6.5-alpha-730

**Review by andrew-welker — APPROVED** [review]

**Comment by batourin** [comment]
Hi All,

I have real hardware - Vaddio cameras that talks some dialect of Visca, I can test and most likely fix...
At least I need it working :-)

**Comment by ndorin** [comment]
Closing for now.  Lack of hardware to test against prevents merging untested code.

**Comment by batourin** [comment]
Hi Neil,
I promised to test it, sorry was busy last week with other web related projects.
I'll give you updates next two days.

**Comment by ndorin** [comment]
Thanks @batourin. There's no huge rush.  The branch would likely need to be updated to include the latest development commits.
Any testing you're able to perform would be helpful, but I know in the past that Vaddio's implementation of VISCA protocol was different enough from the Sony standard to not provide feedback for many properties

**Pull request closed without merging**
