### PR TITLE
Update CiscoSpark to work with ce9.13

### LINKED ISSUE #277: [FEATURE]-Update CiscoSparkCodec class to accommodate ce 9.13
**Is your feature request related to a problem? Please describe.**
The current implementation of CiscoSparkCodec doesn't accommodate ce 9.13

Currently, there's a whitespace issue, in which ce versions pre 9.13 are formatted in json as `"PropertyName":{` but the 9.13 implementation is formatted as `"PropertyName": {`  That string is being used to determine which return to deserialize to.

**Describe the solution you'd like**
Test with live codec to determine issues
Fix the parsing issue by adding an "or"

**Describe alternatives you've considered**
No alternative - this must be exposed in essentials

### PR DESCRIPTION
**Pull request by TrevorPayne**
Resolves #277

Tested on live equipment - adds an or to each of the if statements that determines which response object is being returned

### CODE REVIEW

**Comment by ndorin** [comment]
I wonder if the best way to handle this going forward would be to deserialize the response into a JObject and check for the presence of the top level object we’re looking for, instead of the basic string comparison we’ve been doing. Then any white space discrepancy would be solved by the deserialization already. 

Certainly a more flexible solution

**Comment by andrew-welker** [comment]
@ndorin @TrevorPayne and I did discuss that. That definitely is the best way forward, but in the interest of having something working and because @TrevorPayne has to give the codec back to Eric in 4 hours, that's an effort that can be undertaken at another time.

**Comment by andrew-welker** [comment]
I think we can keep that issue open and mention it there, and when someone has time, they can work on that effort.

**Comment by andrew-welker** [comment]
Added a new issue to track the parsing change effort.

**Pull request merged**
