### PR TITLE
Change ReleaseAndMakeRoute to use IRoutingSinkNoSwitching instead of IRoutingInputs

### PR DESCRIPTION
**Pull request by ngenovese11**

### CODE REVIEW

**Comment by andrew-welker** [comment]
@ndorin no. You haven't missed something. Thiis hasn't been updated since we had that discussion with @ngenovese11 .

**Comment by ngenovese11** [comment]
@andrew-welker @ndorin check out the additional interface I added.  I think that a blank interface of IRoutingSink is much more readable then having to know that IRoutingSinkWithSwitching inherits from IRoutingSinkNoSwitching, I also added a protection later on if a device happens to be a RoutingSinkWithNoSwitching and an IRouter

**Comment by andrew-welker** [comment]
How about we make IRoutingSinkWithSwitching inherit directly from IRoutingSink, then mark IRoutingSinkNoSwitching as obsolete? No sense in having 2 interfaces that are essentially the same.

**Comment by ngenovese11** [comment]
heh _essentially_ I don't disagree.  My other thought was to make IRoutingSinkNoSwitching internal, because I can't imagine anywhere outside of Essentials is using it...

**Comment by andrew-welker** [comment]
Ha. I say Obsolete precisely because we don't know where it's been used outside of Essentials.

**Comment by ngenovese11** [comment]
Probably smart... OK so changing IRoutingSinkWithSwitching to inherit IRoutingSink is doable, but I had to update the VTC room, DualDisplayRoom and Huddle spaces to accommodate since they were implicitly assigning from IRoutingSinkWithSwitching to IRoutingSinkNoSwitching... please review, it might not be worth it to change

**Pull request merged**
